# Generated by Django 2.0.5 on 2018-05-10 06:30

import apps.categorys.models
import datetime
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.categorys.models.BillType, verbose_name='账目类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='账目金额')),
                ('record_date', models.DateField(default=datetime.date.today, verbose_name='记录时间')),
                ('remarks', models.CharField(max_length=140, verbose_name='备注信息')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
