# Generated by Django 2.0.5 on 2018-05-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('0', 'OUTGO'), ('1', 'INCOME')], default='0', max_length=1, verbose_name='账目类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='账目金额')),
                ('record_date', models.DateField(auto_now=True, verbose_name='记录时间')),
                ('remarks', models.CharField(max_length=140, verbose_name='备注信息')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorys.Categorys', verbose_name='明细分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账目所属用户')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
