# Generated by Django 2.0.5 on 2018-05-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True, verbose_name='是否默认分类')),
                ('bill_type', models.CharField(choices=[('0', 'OUTGO'), ('1', 'INCOME')], default='0', max_length=1, verbose_name='账目类型')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorys.Categorys', verbose_name='父级分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='自定义分类所属用户')),
            ],
            options={
                'db_table': 'categorys',
            },
        ),
    ]
