# Generated by Django 2.0.5 on 2018-05-10 15:03

import apps.categorys.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认分类')),
                ('bill_type', enumfields.fields.EnumIntegerField(default=0, enum=apps.categorys.models.BillType, verbose_name='账目类型')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorys.Categorys', verbose_name='父级分类')),
            ],
            options={
                'db_table': 'categorys',
                'ordering': ['-modify_time'],
            },
        ),
    ]
